apiVersion: v1
kind: Pod
metadata:
  name: broken-storage
spec:
  containers:
    - name: nginx
      image: nginx:1.25
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: storage-yang-salah