apiVersion: v1
kind: Pod
metadata:
  name: polinux-stress
  labels:
    app: polinux-stress
spec:
  containers:
    - name: polinux-stress
      image: polinux/stress
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "300M", "--vm-hang", "1"]
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "50m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"

